set_property MARK_DEBUG true [get_nets {led_o_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/pll_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {led_o_OBUF[0]} {led_o_OBUF[1]} {led_o_OBUF[2]} {led_o_OBUF[3]} {led_o_OBUF[4]} {led_o_OBUF[5]} {led_o_OBUF[6]} {led_o_OBUF[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
