set_property MARK_DEBUG true [get_nets {led_o_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {led_o_OBUF[7]}]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
